ports:
  - port: 8001
    onOpen: open-preview

tasks:
  - name: Start Redis Stack
    init: |
     docker-compose pull
    command: |
     docker-compose up -d
     gp sync-done finished
    openMode: split-left
  - name: Prepare application
    init: |
      pip install -r requirements.txt
    command: |
      gp sync-await finished
    openMode: split-right

vscode:
  extensions:
    - ms-python.python