version: "3.9"
services:
  redis:
    container_name: redis_om_python_demo
    image: "redis/redis-stack:latest"
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
